apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{ values.name }}
  name: ${{ values.name }}-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ${{ values.name }}
