"""
Runs the integration tests exactly once and reports the result to the PR —
deliberately a single pytest invocation with one JUnit XML output, parsed with
a real XML parser. The behave-based version of this script (fermentation-station-agent)
had two stacked bugs: it ran the test suite *twice* (once per output format), so the
displayed log and the reported counts could come from two different runs racing the
same not-yet-ready service; and it counted results with `grep -c` against compact
JSON, which counts matching *lines* (0 or 1) rather than occurrences. Neither failure
mode is possible here by construction.
"""

import os
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import httpx

REPO_SLUG = os.environ["REPO_SLUG"]
PR_NUMBER = os.environ["PR_NUMBER"]
COMMIT_SHA = os.environ["COMMIT_SHA"]
GH_TOKEN = Path("/etc/github/token").read_text().strip()

JUNIT_PATH = Path("results.xml")
COMMENT_MARKER = "<!-- integration-test-results -->"


def run_tests() -> int:
    result = subprocess.run(
        [
            "pytest",
            "integration_tests/",
            f"--junitxml={JUNIT_PATH}",
            "-v",
        ],
        capture_output=True,
        text=True,
    )
    Path("pytest-output.txt").write_text(result.stdout + result.stderr)
    return result.returncode


def parse_results() -> dict:
    if not JUNIT_PATH.exists():
        return {"tests": 0, "failures": 0, "errors": 0, "skipped": 0}
    root = ET.parse(JUNIT_PATH).getroot()
    suites = [root] if root.tag == "testsuite" else root.findall("testsuite")
    return {
        "tests": sum(int(s.attrib.get("tests", 0)) for s in suites),
        "failures": sum(int(s.attrib.get("failures", 0)) for s in suites),
        "errors": sum(int(s.attrib.get("errors", 0)) for s in suites),
        "skipped": sum(int(s.attrib.get("skipped", 0)) for s in suites),
    }


def build_report_body(counts: dict) -> str:
    passed = counts["tests"] - counts["failures"] - counts["errors"] - counts["skipped"]
    log = Path("pytest-output.txt").read_text()[-6000:]
    return f"""{COMMENT_MARKER}
## Integration Test Results
| Status | Count |
| :--- | :--- |
| Passed | {passed} |
| Failed | {counts['failures']} |
| Errors | {counts['errors']} |
| Skipped | {counts['skipped']} |
| Total | {counts['tests']} |

<details>
<summary><b>Click to see full test logs</b></summary>

```text
{log}
```
</details>

*Generated by Kubernetes Job: {os.environ.get('HOSTNAME', 'unknown')}*
"""


def find_existing_comment_id(headers: dict) -> int | None:
    """Find our own prior report comment, so re-running the Job (retries, rapid
    re-pushes racing image propagation) updates it instead of piling up duplicates —
    same find-or-update approach as actions.yml's ci-summary comment."""
    page = 1
    while True:
        response = httpx.get(
            f"https://api.github.com/repos/{REPO_SLUG}/issues/{PR_NUMBER}/comments",
            headers=headers,
            params={"per_page": 100, "page": page},
        )
        if response.status_code != 200:
            return None
        comments = response.json()
        for comment in comments:
            if COMMENT_MARKER in comment.get("body", ""):
                return comment["id"]
        if len(comments) < 100:
            return None
        page += 1


def post_comment(body: str) -> None:
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {GH_TOKEN}",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    existing_id = find_existing_comment_id(headers)
    if existing_id is not None:
        httpx.patch(
            f"https://api.github.com/repos/{REPO_SLUG}/issues/comments/{existing_id}",
            headers=headers,
            json={"body": body},
        )
    else:
        httpx.post(
            f"https://api.github.com/repos/{REPO_SLUG}/issues/{PR_NUMBER}/comments",
            headers=headers,
            json={"body": body},
        )


def post_status(state: str, description: str) -> None:
    httpx.post(
        f"https://api.github.com/repos/{REPO_SLUG}/statuses/{COMMIT_SHA}",
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {GH_TOKEN}",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        json={
            "state": state,
            "context": "kubernetes/integration-tests",
            "description": description,
        },
    )


def main() -> None:
    run_tests()
    counts = parse_results()
    body = build_report_body(counts)
    post_comment(body)

    failed = counts["failures"] > 0 or counts["errors"] > 0
    state = "failure" if failed else "success"
    passed = counts["tests"] - counts["failures"] - counts["errors"] - counts["skipped"]
    post_status(
        state,
        f"Integration tests: {passed} passed, {counts['failures']} failed, {counts['errors']} errors",
    )
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
